<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%; display: block; shape-rendering: auto;" width="224px" height="224px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<g transform="translate(50 50)">
  <g transform="scale(0.7)">
    <g transform="translate(-50 -50)">
      <g>
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="0.641025641025641s"></animateTransform>
        <path fill-opacity="0.8" fill="#80cf47" d="M50 50L50 0A50 50 0 0 1 100 50Z"></path>
      </g>
      <g>
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="0.8547008547008548s"></animateTransform>
        <path fill-opacity="0.8" fill="#cc467e" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(90 50 50)"></path>
      </g>
      <g>
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="1.282051282051282s"></animateTransform>
        <path fill-opacity="0.8" fill="#cc6c46" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(180 50 50)"></path>
      </g>
      <g>
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="2.564102564102564s"></animateTransform>
        <path fill-opacity="0.8" fill="#46b8cc" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(270 50 50)"></path>
      </g>
    </g>
  </g>
</g>
<!-- [ldio] generated by https://loading.io/ --></svg>