import { Shop } from "./types";

export const mockData: Shop[] = [
    {
        id: 1,
        name: "Dicksy",
        url: "https://dicksy.ru",
        address: "Moscow, 2-ya Vladimirskaya, 20",
        comment: "Good shop",
    },
    {
        id: 2,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 3,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 4,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 5,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 6,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 7,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 8,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 9,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 10,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 11,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 12,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 13,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 14,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 15,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 16,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 17,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 18,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 19,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 20,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 21,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 22,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 23,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 24,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 25,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 26,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 27,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 28,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 29,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
    {
        id: 30,
        name: "Perekrestok - the most longest shop with the most longest name in the most longest world",
        address: "Moscow, Tverskaya, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
        id: 31,
        name: "Karusel",
        url: "https://karusel.ru",
        address: "Moscow, 2-ya Vladimirskaya, 30",
    },
    {
        id: 32,
        name: "Auchan",
        address: "Moscow, Molostovikh, 2",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        id: 33,
        name: "Ikea",
        url: "https://ikea.ru",
        address: "Moscow, Shosse entuziastov, 10",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ",
    },
];