CREATE ROLE api WITH
    NOLOGIN
    NOSUPERUSER
    NOINHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE USER api_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    VALID UNTIL '2020-12-31 19:12:14+03';

GRANT api TO api_user;

ALTER USER api_user SET search_path = "budget";
ALTER ROLE api SET search_path = "budget";

CREATE SCHEMA budget
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA budget TO postgres;

GRANT USAGE ON SCHEMA budget TO api;

ALTER DEFAULT PRIVILEGES IN SCHEMA budget
    GRANT INSERT, SELECT, UPDATE ON TABLES TO api;

GRANT SELECT ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;

GRANT UPDATE ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;

GRANT DELETE ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;

-- grant privileges on tables

SET search_path TO budget;

GRANT INSERT, SELECT, UPDATE ON TABLE goods TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE goods_categories TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE goods_details TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE income TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE income_type TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE notifications TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE notifications_queue TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE purchases TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE sessions TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE severity_type TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE shops TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE user_data TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE user_group TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE user_profile TO api;
GRANT INSERT, SELECT, UPDATE ON TABLE users TO api;
