CREATE USER api_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    VALID UNTIL '2020-12-31 19:12:14+03';

GRANT USAGE ON SCHEMA budget to api_user;

GRANT SELECT ON ALL TABLES IN SCHEMA budget to api_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api_user;

GRANT UPDATE ON ALL TABLES IN SCHEMA budget to api_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api_user;

GRANT DELETE ON ALL TABLES IN SCHEMA budget to api_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api_user;
