CREATE ROLE api WITH
    NOLOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

CREATE USER api_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    VALID UNTIL '2020-12-31 19:12:14+03';

GRANT api TO api_user;

ALTER USER api_user SET search_path = "budget";

CREATE SCHEMA budget
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA budget TO postgres;

GRANT USAGE ON SCHEMA budget TO api;

ALTER DEFAULT PRIVILEGES IN SCHEMA budget
    GRANT INSERT, SELECT, UPDATE ON TABLES TO api;

GRANT SELECT ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;

GRANT UPDATE ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;

GRANT DELETE ON ALL TABLES IN SCHEMA budget to api;
ALTER DEFAULT PRIVILEGES IN SCHEMA budget GRANT SELECT ON TABLES TO api;
