CREATE TABLE IF NOT EXISTS user_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    surname VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS user_profile (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    path_to_photo VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS user_group (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(3000),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP,
    is_removed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_data_id INTEGER NOT NULL,
  user_profile_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP,
  last_online_at TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  description VARCHAR(3000),
  user_group_id INTEGER NOT NULL,

  FOREIGN KEY (user_data_id) REFERENCES user_data (id),
  FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
  FOREIGN KEY (user_group_id) REFERENCES user_group (id)
);

ALTER TABLE user_group ADD COLUMN added_by_user_id INTEGER;

ALTER TABLE user_group
ADD FOREIGN KEY (added_by_user_id)
REFERENCES users(id);